version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    healthcheck:
        test: curl --fail -s http://localhost:9200 || exit 1
        interval: 10s
        timeout: 10s
        retries: 5
    volumes:
      - esdata:/usr/share/elasticsearch/data

  backend:
    build: ./backend
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - "./backend:/opt/app"
      - "/opt/app/node_modules"
    depends_on:
      - elasticsearch

  frontend:
    build: ./frontend
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 4200:4200
    volumes:
      - "./frontend:/opt/app"
      - "/opt/app/node_modules"
    depends_on:
      - backend

volumes:
  esdata:
    driver: local
